Change country name Burma to Myanmar. Updating North Macedonia and Es…
UKForeignOffice/loi-application-service pull request #100
Opened 2019-06-20 13:27 UTC by cmcgandy

…watini

2019-06-24 14:00 UTC, simonmoore100 commented on database_change_log/updateCountryList.sql
> +INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (34, 'Myanmar', false, 'Myanmar');
Are Casebook updating it at their end then?

2019-06-24 14:02 UTC, simonmoore100 requested changes
Check my comments before merging.

2019-06-24 14:02 UTC, simonmoore100 commented on database_change_log/updateCountryList.sql
> +INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (195, 'Eswatini', false, 'Swaziland');
Can you move this up so its in alphabetical order now. Also, before this is ran is prod can you do a select and compare against this list to ensure there aren't any more changes?

2019-06-25 15:22 UTC, smulvenna approved these changes

2019-06-27 10:26 UTC, merged