Feat/eia 208 accessibility testing
UKForeignOffice/loi-application-service pull request #300
Opened 2021-10-28 16:18 UTC by RichardBray

https://jira.digital.csd.fcdo.gov.uk/browse/EIA-208

2021-10-29 11:07 UTC, jenbutongit requested changes

2021-10-29 11:07 UTC, jenbutongit commented on cypress/integration/a11y.spec.js
> +            cy.get('.govuk-button--start').contains('Start now').click();
I would recommend changing these matchers. Class matching is quite flakey in general. 

I'm using https://testing-library.com/docs/cypress-testing-library/intro/. You should be familiar with it from react-testing-library. I try to exclusively use `findByLabelText` or `findByRole`. It gives you an added layer of accessibility confidence, since you are finding/getting by what is accessible to screenreaders. https://kentcdodds.com/blog/common-mistakes-with-react-testing-library#not-using-byrole-most-of-the-time

2021-10-29 11:54 UTC, jenbutongit requested changes

2021-10-29 11:54 UTC, jenbutongit commented on cypress/integration/a11y.spec.js
> +            cy.wait(500);
cypress waits on its own, adding a hardcoded wait will contribute to flakiness. Is there an element that pops up? you can do `cy.get('.component-that-hasnt-appeared-yet', {timeout: ..})` if the default timeout isn't long enough.

2021-10-29 11:54 UTC, jenbutongit commented on cypress/integration/a11y.spec.js
> +            clickContinueBtn();
I know that these are just a11y tests, but I have no idea what the first radio is, and what it does, where it goes etc. 

With testing library, it would look like this 
```suggestion
            const { getByLabelText, getByRole } = cy;
            getByLabelText('First Item').click()
            getByRole('button').click()
```
And then I would stop nesting it inside a function, since it is just as readable as "checkFirstRadioAndClickContinue" (if not more), and is more flexible.

2021-10-29 11:54 UTC, jenbutongit commented on cypress/integration/a11y.spec.js
> +                    checkFirstRadioAndClickContinue();
what about the other routes?

2021-10-29 11:54 UTC, jenbutongit commented on docs/automated-a11y-testing.md
> +```
did you mean to keep ... here?

this should resolve the syntax highlighting issue
```suggestion
```json5
{
  "baseUrl": "https://www.demo.legalisation.fcodev.org.uk",
  // ...
}
```
```

2021-10-29 11:54 UTC, jenbutongit commented on views/eApostilles/checkUploadedDocuments.ejs
> +    <h2 class="heading-medium govuk-!-margin-top-2">Cost</h2>
it looks like there are upto 3 `h2`s on this page now. Is that right?

2021-10-29 11:54 UTC, jenbutongit commented on views/eApostilles/openEApp.ejs
> +                <h2 class="heading-medium">Download documents</h2>
there are quite a few on this page too. Is this semantically correct?

2021-10-29 12:51 UTC, RichardBray commented on cypress/integration/a11y.spec.js
> +                    checkFirstRadioAndClickContinue();
Good shout. I didn't feel the need to test them since they are just static exit pages but I can do them as well.

2021-10-29 12:54 UTC, RichardBray commented on docs/automated-a11y-testing.md
> +```
This is a neat trick. json5 looks like a more advanced version of jsonc. Have you used it in any projects before?

2021-10-29 13:00 UTC, RichardBray commented on views/eApostilles/checkUploadedDocuments.ejs
> +    <h2 class="heading-medium govuk-!-margin-top-2">Cost</h2>
Yep, that's correct. I was under the assumption you could only have one h1 but multiple h2-6's on a page. Maybe it's different for GOV pages?

2021-10-29 13:31 UTC, RichardBray commented on cypress/integration/a11y.spec.js
> +            cy.wait(500);
to be fair I didn't test it without the wait, I added it because I assumed it was necessary to wait for the file to actually upload but looks like it works without it 👍

2021-10-29 13:35 UTC, jenbutongit commented on views/eApostilles/checkUploadedDocuments.ejs
> +    <h2 class="heading-medium govuk-!-margin-top-2">Cost</h2>
that's right. If all 3 headings/sections are as important as each other that's fine. Some users using screen readers like to navigate by headings so it's just good to keep in mind

2021-10-29 15:11 UTC, jenbutongit commented on docs/automated-a11y-testing.md
> +```
Not really, I think I always end up using transpiling tools that will get rid of json5 (or js/ts) trailing object commas, but I know it exists (and GitHub will give you nicer parsing if you have comments etc)

2021-11-01 11:43 UTC, jenbutongit commented on cypress/integration/a11y.spec.js
> +                for (var i = 0; i < TOTAL_ELIBIGILITY_QUESTIONS - 1; ++i) {
this can start on `i = 1` so there's no need to `-1` from eligibility Qs

2021-11-01 11:49 UTC, jenbutongit requested changes

2021-11-01 11:49 UTC, jenbutongit commented on cypress/integration/a11y.spec.js
> +
you can destructure up here all of the methods that you're using frequently like 
`const { findByLabelText, findByRole, setCookie } = cy` to improve the readability

2021-11-01 14:39 UTC, jenbutongit approved these changes

2021-11-01 14:44 UTC, merged