Add rejection reasons to UAT branch
UKForeignOffice/loi-application-service pull request #302
Opened 2021-11-02 16:22 UTC by RichardBray

2021-11-03 15:27 UTC, simonmoore100 requested changes
The functionality looks to work fine when I run it locally. Just fix up a couple of those typos in the text and we are good to go.

2021-11-03 15:27 UTC, simonmoore100 commented on views/partials/rejectionReasons.ejs
> +                            Some documents cannot be legalised by the e-Apostille service. You may be able to [use the
Remove the square bracket

2021-11-03 15:27 UTC, simonmoore100 commented on views/partials/rejectionReasons.ejs
> +                        We are unable to legalise your document(s) because the date on the cover sheet does not match the date the digital
This sentence doesn't make sense, to me at least

2021-11-03 15:27 UTC, simonmoore100 commented on views/partials/rejectionReasons.ejs
> +                            country of the UK where the document has been certified.
'country of the UK'? Is this correct?
I get it's referring to England / Scotland / Wales etc but I had to read it a few times to understand

2021-11-03 15:27 UTC, simonmoore100 commented on views/partials/rejectionReasons.ejs
> +                        or Department for Business, Innovation and Skills, contains the wording 'Signature not verified', 'Validity unknown' or
Keep the single quote type consistent

2021-11-08 10:15 UTC, RichardBray commented on views/partials/rejectionReasons.ejs
> +                            country of the UK where the document has been certified.
Yeah, it does sound a bit weird. I had to re-dead it a couple of times but if it's read with the other sentences, (not in isolation), it does make sense.

2021-11-08 10:29 UTC, simonmoore100 approved these changes
LGTM

2021-11-08 12:20 UTC, merged