fix: add various small fixes to the code
UKForeignOffice/loi-application-service pull request #406
Opened 2022-06-09 14:20 UTC by RichardBray

# Description

The purpose of this PR is to fix a few small typos and address an issue with a file limit error.

I've tried my best to make the code as readable as possible but if any of it doesn't make sense please don't hesitate to ask.

2022-06-09 17:31 UTC, jenbutongit commented on api/controllers/FileUploadController.js
> +            let genericErrors = req.flash('genericErrors') ?? [];
💪 `??`

2022-06-09 17:41 UTC, jenbutongit requested changes

2022-06-09 17:41 UTC, jenbutongit commented on api/controllers/FileUploadController.js
> +                genericErrors = req.flash('genericErrors');
what happens when there are genericErrors, but you don't have max file limit errors? won't this end up replacing them?

2022-06-09 17:41 UTC, jenbutongit commented on api/controllers/FileUploadController.js
> +            const maxFileLimitErrorExists = genericErrors.includes(POST_UPLOAD_ERROR_MESSAGES.fileCountError);
you have a lot of logic finding/dealing with a specific error. should fileCountError have it's own req.flash key?

2022-06-10 08:35 UTC, RichardBray commented on api/controllers/FileUploadController.js
> +                genericErrors = req.flash('genericErrors');
ah that's a fair point, I'll address that

2022-06-10 08:35 UTC, RichardBray commented on api/controllers/FileUploadController.js
> +            const maxFileLimitErrorExists = genericErrors.includes(POST_UPLOAD_ERROR_MESSAGES.fileCountError);
yep I can do that, might fix the issue that you raised in the previous comment as well

2022-06-10 14:20 UTC, jenbutongit approved these changes

2022-06-10 14:28 UTC, merged